name: kontri
description: "A financial contribution tracker app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  device_calendar: ^4.3.3
  intl: ^0.19.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any       
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256